# Generated by Django 2.1.15 on 2020-12-08 19:26

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=base.models.recipe_image_file_path),
        ),
    ]
